### ISSUE TITLE
Logging out of the app

### ISSUE THREAD

**Issue by HoracekPetr** [talhaoz/JetPackCompose-LoginAndBottomBar#1]
Hey, I had a problem similar to yours, found your solution (this one, using two nav hosts) and it works, but - when you log in, you enter the second nav hosts (AppScaffold Nav host) with no way to get back to Login Screen (or no way I am aware of). Navigating to LoginScreen.route would crash as it's not a route in AppScaffold Nav Host. 

I was trying to implement a log out function and I am stuck at this problem.

**Comment by talhaoz** [comment]
Hello, yes I am also faced with this problem. I even created a ticket to Google Issue Tracker about this. But currently, there is no valid solution for this. As they said, they are still improving Compose Navigation. I go around this problem by restarting the application. But if you want to stay in the application after signing out, I have no other suggestion. If you can find anything, please also comment here :)

**Comment by newmanw** [comment]
Although I don't think this is the recommended approach, this can be handled by hoisting the logout action back up to where you have both nav controllers.  See #2.

**Comment by talhaoz** [comment]
> Although I don't think this is the recommended approach, this can be handled by hoisting the logout action back up to where you have both nav controllers. See #2.

Nice one, Thanks a lot !!

**Comment by talhaoz** [comment]
> Although I don't think this is the recommended approach, this can be handled by hoisting the logout action back up to where you have both nav controllers. See #2.

Nice one, Thanks a lot !!
